In [ ]:
print("hello")

hello


In [ ]:
print("how are you")

how are you


In [ ]:
def hello():
  print("hello how are you")

In [ ]:
hello()

hello how are you


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
a=[1,2,3.4,"hello"]
a

[1, 2, 3.4, 'hello']

In [ ]:
np.array(a)

array(['1', '2', '3.4', 'hello'], dtype='<U32')

In [ ]:
l=[(1,2,3),(4,5,6),(7,8,9)]
l

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.zeros((3,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.ones((6,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
np.random.rand(10)

array([0.68431394, 0.79509483, 0.29566539, 0.22275677, 0.02606064,
       0.40873119, 0.72074331, 0.4363805 , 0.76182438, 0.30350503])

In [ ]:
np.random.randn(10)

array([-0.30492893,  0.69023322,  0.04956418, -0.66083235,  0.07238764,
        0.93123788,  0.49443449,  0.7382072 ,  1.03288043, -0.68415435])

In [ ]:
np.random.randint(10,20,10)

array([15, 15, 10, 10, 16, 11, 17, 13, 17, 17])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[7]

np.int64(18)

In [ ]:
arr[1:4]

array([12, 13, 14])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2]

array([11, 12, 13, 14, 15])

In [ ]:
arr[0,4]

np.int64(5)

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3: , 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [ ]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
l=[10,20,30,40]
arr=np.array(l)
arr+10

array([20, 30, 40, 50])

In [ ]:
new_var = arr + 10
new_var

array([20, 30, 40, 50])

In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice=slice+10
slice

array([11, 12, 13, 14, 15])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[4:6]*10

array([50, 60])

In [ ]:
a
b=a.copy()

In [ ]:
b[0]=23

In [ ]:
b

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
m=np.array([[1,2],[3,4]])
p=np.array([[5,6],[7,8]])

In [ ]:
m

array([[1, 2],
       [3, 4]])

In [ ]:
p

array([[5, 6],
       [7, 8]])

In [ ]:
m*p

array([[ 5, 12],
       [21, 32]])

In [ ]:
#m@p
np.dot(m,p)

array([[19, 22],
       [43, 50]])

In [ ]:
m.T

array([[1, 3],
       [2, 4]])

In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])

In [ ]:
np.vstack((A,B))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((A,B))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((A,B))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
np.concatenate((A,B))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]