In [ ]:
import numpy as np

In [ ]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [ ]:
b=np.sum(s,axis=1)
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
s[0:3,0:3]


array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [ ]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
import numpy as np

In [ ]:
#columns= [age,math marks , science marks]
data=np.array([
    [18,85,78],
    [19,92,88], #students
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [ ]:
data.shape

(5, 3)

In [ ]:
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
np.max(data[:,2])

np.int64(95)

In [ ]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
data=np.array([
    [18,85,78],
    [19,92,88], #students
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [ ]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [ ]:
len(data[data[:,0]<19])

3

In [ ]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [ ]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])